# Boot Animation
TARGET_SCREEN_HEIGHT := 1280
TARGET_SCREEN_WIDTH := 720
#DEVICE_RESOLUTION := 720x1280
#TARGET_BOOT_ANIMATION_RES := 720
#TARGET_BOOTANIMATION_PRELOAD := true
#TARGET_BOOTANIMATION_TEXTURE_CACHE := true
